/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Empresa.adm.view;

import java.awt.Color;
import java.awt.Event;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author ciacelo
 */
public class LoginAdm extends javax.swing.JFrame {

    /**
     * Creates new form LoginAdm
     */
    public LoginAdm() {
        initComponents();
        setIcone();
        jPasswordLogin.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
				if(ke.getKeyCode() == Event.ENTER){
                                    if (jtextUsuario.getText().equals("Marcelo") && new String(jPasswordLogin.getPassword()).trim().equals("12345")){
                                        MenuAdm menu = new MenuAdm();
                                        menu.setVisible(true);
                                        dispose();
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos.");
                                    }
                                                    
                                }
            }
            
        });
                

        //foreground da caixa de texto senha.
        TextPrompt tp2 = new TextPrompt("     Senha", jPasswordLogin);
        tp2.setForeground(new Color(128, 128, 128));
        tp2.setBackground(new Color(255, 255, 255));
        tp2.setFont(new Font("Segoe UI Semilight", Font.PLAIN, 16));
        jPasswordLogin.setToolTipText("");
	jPasswordLogin.setFont(new Font("Segoe UI Semilight", Font.PLAIN, 16));
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jButtonLogin = new javax.swing.JButton();
        jtextUsuario = new javax.swing.JTextField();
        jPasswordLogin = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADM_Eagle");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/eaglejr/adm/view/imagens/BotaoLoginTxt.png"))); // NOI18N
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButtonLogin);
        jButtonLogin.setBounds(630, 330, 260, 20);

        jtextUsuario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jtextUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jtextUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtextUsuario.setText("     Nome de usuário");
        jtextUsuario.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jtextUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtextUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtextUsuarioFocusLost(evt);
            }
        });
        jDesktopPane2.add(jtextUsuario);
        jtextUsuario.setBounds(630, 230, 260, 30);

        jPasswordLogin.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jPasswordLogin.setToolTipText("");
        jPasswordLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordLoginFocusGained(evt);
            }
        });
        jDesktopPane2.add(jPasswordLogin);
        jPasswordLogin.setBounds(630, 270, 260, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/eaglejr/adm/view/imagens/BkgLogin.jpg"))); // NOI18N
        jDesktopPane2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1020, 500);

        getContentPane().add(jDesktopPane2, "card2");

        setSize(new java.awt.Dimension(990, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordLoginFocusGained
        
    }//GEN-LAST:event_jPasswordLoginFocusGained

    private void jtextUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtextUsuarioFocusGained
        
        if(jtextUsuario.getText().equals("     Nome de usuário")){
            jtextUsuario.setText("");
            jtextUsuario.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jtextUsuarioFocusGained

    private void jtextUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtextUsuarioFocusLost
        if(jtextUsuario.getText().equals("")){
           jtextUsuario.setForeground(Color.GRAY);
           jtextUsuario.setText("     Nome de usuário");
        }
    }//GEN-LAST:event_jtextUsuarioFocusLost

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        if (new String(jPasswordLogin.getPassword()).trim().equals("12345")){
            MenuAdm menu = new MenuAdm();
            menu.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos.");
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordLogin;
    private javax.swing.JTextField jtextUsuario;
    // End of variables declaration//GEN-END:variables

    private void setIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IconeEagle.png")));
    }
}
